### ISSUE TITLE
THERE IS NO CODE YET | Regarding instructions

### ISSUE THREAD

**Issue by Diorski** [irohia/DidNotRespond#1]
Instructions unclear, I would like to go ahead and experiment if this code and feature could work. Not sure on how to use it tho.

**Comment by irohia** [comment]
This was a repo I created as an idea, I haven't found the time to work on it yet.
My apologies! :(

**Comment by irohia** [comment]
Going to pin this as well, because I'm sure someone else will ask the same thing.
